/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lab.leleonz.consoletester;

import java.io.IOException;

import com.fasterxml.jackson.databind.ObjectMapper;

import lab.leleonz.consoletester.RestApiCaller.NativeHttpClientImpl;
import lab.leleonz.consoletester.RestApiCaller.CustomerCrudCaller.CustomerCrudBase;
import lab.leleonz.consoletester.RestApiCaller.CustomerCrudCaller.SpringBootExampleCustomerCrud;
import lab.leleonz.consoletester.TestingGrounds.SpringBootExample_CustomerCrud_TestApp;
import lab.leleonz.consoletester.TestingGrounds.TestingGroundBase;

public class App {
    public static void main(String[] args) throws IOException, InterruptedException {
        CustomerCrudBase springBootCustomerCrud = new SpringBootExampleCustomerCrud(new NativeHttpClientImpl(), new ObjectMapper());
        TestingGroundBase testingGround = new SpringBootExample_CustomerCrud_TestApp(springBootCustomerCrud);

        testingGround.run();
    }
}
