/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lab.leleonz.springbootapi;

import org.junit.jupiter.api.Test;

class AppTest {

    @Test 
    void contextLoad() {
        
    }
    
}
